language: cpp

os:
  - linux
  - osx

compiler:
  ######################
  # Compilers
  ######################
  - gcc
  - clang

before_script:
  ######################
  # Create build directory
  ######################
  - git clone https://github.com/google/googletest

script:
  ############################################################################
  # Build main and tests
  ############################################################################
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
  - make
  - make test
